### ISSUE TITLE
Instantiating and/or querying the model results in 404

### ISSUE THREAD

**Issue by samwinslow** [runwayml/hosted-models#3]
Hey there. Not sure if this is a bug in the JS library, Runway's backend, or if I'm getting silently rate-limited— so please let me know if there is a better place to post this!

My app encounters a PermissionDeniedError (as defined in src/HTTPErrors.ts:23) with the message 'Model not found. Make sure the url is correct and that the model is "active".' The API key is valid.

The network activity shows failures (404) for:
- GET `https://MODEL-NAME.hosted-models.runwayml.cloud/v1/`
- POST `https://MODEL-NAME.hosted-models.runwayml.cloud/v1/query`

Using `waitUntilAwake` makes no difference, as that call will fail, too.

Every time I encounter this error, I find that the hosted model has become Inactive, as shown on the dashboard at `https://app.runwayml.com/hosted-models`. I can then toggle it to Active, and perhaps make 1 request through my app before the model is once again Inactive.

This behavior makes me think there might be either a backend issue or some kind of rate-limiting. For reference, I have been making around 50-60 requests/hour while testing. If rate-limiting is the case here, it would be nice if the model returned 429 Too Many Requests instead of silently inactivating.

**Comment by brannondorsey** [comment]
Thanks for submitting this report. I can try and help debug here in GH issues. Feel free to reach out to us via the chat bubble at [support.runwayml.com](https://support.runwayml.com) too and we can discuss details about your user account that may be contributing to this.

> Every time I encounter this error, I find that the hosted model has become Inactive, as shown on the dashboard at https://app.runwayml.com/hosted-models. I can then toggle it to Active, and perhaps make 1 request through my app before the model is once again Inactive.

This is interesting, I haven't seen this before. Are you able to have multiple hosted models "Active" at once? Non-subscribed users can only have one hosted-model active at a time. It's possible there is an issue on our end that is incorrectly marking hosted-models as inactive when it shouldn't.

> have been making around 50-60 requests/hour while testing. If rate-limiting is the case here, it would be nice if the model returned 429 Too Many Requests instead of silently inactivating.

As for rate-limiting, we do have a relatively high global rate limit on hosted-models, however that returns a 429 and it sounds like you haven't hit it. Our rate-limiting functionality also wouldn't mark your hosted-model as inactive even if it were triggered.

Like I said, I'm happy to take this up in a more real-time based conversation in our support chat. I can then report our findings back here for other folks to read in the future.

**Comment by samwinslow** [comment]
Hey Brannon, thanks. I have only one hosted model in my account which is on a paid plan. Will reach out via the live chat.

**Comment by samwinslow** [comment]
This was resolved via a Support chat and turned out not to be a problem with the Hosted Models library.

**Comment by brannondorsey** [comment]
For future reference, Hosted Models are automatically deactivated if the user has a $0 credit balance. Topping up the credit balance and re-enabling the Hosted Model should get things working again.

Thanks for raising this issue @samwinslow!
